"""initial

Revision ID: ce67598aaf6f
Revises:
Create Date: 2026-04-27 22:22:38.420058

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce67598aaf6f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$ language 'plpgsql';"
    )
    op.create_table(
        "agent_message_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("message_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("client_id", sa.String(length=255), nullable=True),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=12, scale=6), server_default="0", nullable=False
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_message_usage_agent_id"), "agent_message_usage", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_message_usage_client_id"), "agent_message_usage", ["client_id"], unique=False
    )
    op.create_index(
        "ix_agent_message_usage_created_at", "agent_message_usage", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_agent_message_usage_message_id"),
        "agent_message_usage",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_message_usage_model_id"), "agent_message_usage", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_message_usage_thread_id"), "agent_message_usage", ["thread_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_message_usage_user_id"), "agent_message_usage", ["user_id"], unique=False
    )
    op.create_table(
        "chat_history",
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=True),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column(
            "messages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("preview", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("thread_id"),
    )
    op.create_index(op.f("ix_chat_history_agent_id"), "chat_history", ["agent_id"], unique=False)
    op.create_index(op.f("ix_chat_history_client_id"), "chat_history", ["client_id"], unique=False)
    op.create_index(op.f("ix_chat_history_user_id"), "chat_history", ["user_id"], unique=False)
    op.create_table(
        "checkpoint_blobs",
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("checkpoint_ns", sa.String(), server_default=sa.text("''"), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("blob", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("thread_id", "checkpoint_ns", "channel", "version"),
    )
    op.create_table(
        "checkpoint_writes",
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("checkpoint_ns", sa.String(), server_default=sa.text("''"), nullable=False),
        sa.Column("checkpoint_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("task_path", sa.String(), server_default=sa.text("''"), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("blob", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("thread_id", "checkpoint_ns", "checkpoint_id", "task_id", "idx"),
    )
    op.create_table(
        "checkpoints",
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("checkpoint_ns", sa.String(), server_default=sa.text("''"), nullable=False),
        sa.Column("checkpoint_id", sa.String(), nullable=False),
        sa.Column("parent_checkpoint_id", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("thread_id", "checkpoint_ns", "checkpoint_id"),
    )
    op.execute(
        "CREATE TRIGGER update_chat_history_updated_at BEFORE UPDATE ON chat_history FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS update_chat_history_updated_at ON chat_history")
    op.drop_table("checkpoints")
    op.drop_table("checkpoint_writes")
    op.drop_table("checkpoint_blobs")
    op.drop_index(op.f("ix_chat_history_user_id"), table_name="chat_history")
    op.drop_index(op.f("ix_chat_history_client_id"), table_name="chat_history")
    op.drop_index(op.f("ix_chat_history_agent_id"), table_name="chat_history")
    op.drop_table("chat_history")
    op.drop_index(op.f("ix_agent_message_usage_user_id"), table_name="agent_message_usage")
    op.drop_index(op.f("ix_agent_message_usage_thread_id"), table_name="agent_message_usage")
    op.drop_index(op.f("ix_agent_message_usage_model_id"), table_name="agent_message_usage")
    op.drop_index(op.f("ix_agent_message_usage_message_id"), table_name="agent_message_usage")
    op.drop_index("ix_agent_message_usage_created_at", table_name="agent_message_usage")
    op.drop_index(op.f("ix_agent_message_usage_client_id"), table_name="agent_message_usage")
    op.drop_index(op.f("ix_agent_message_usage_agent_id"), table_name="agent_message_usage")
    op.drop_table("agent_message_usage")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column")
    # ### end Alembic commands ###
