/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentConfigRouteImport } from './routes/agent-config'
import { Route as React19DemoRouteImport } from './routes/react19-demo'
import { Route as AgentAgentIdRouteImport } from './routes/agent/$agentId'
import { Route as ChatAgentIdRouteImport } from './routes/chat/$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentConfigRoute = AgentConfigRouteImport.update({
  id: '/agent-config',
  path: '/agent-config',
  getParentRoute: () => rootRouteImport,
} as any)
const React19DemoRoute = React19DemoRouteImport.update({
  id: '/react19-demo',
  path: '/react19-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAgentIdRoute = AgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAgentIdRoute = ChatAgentIdRouteImport.update({
  id: '/chat/$agentId',
  path: '/chat/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-config': typeof AgentConfigRoute
  '/react19-demo': typeof React19DemoRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/chat/$agentId': typeof ChatAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-config': typeof AgentConfigRoute
  '/react19-demo': typeof React19DemoRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/chat/$agentId': typeof ChatAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-config': typeof AgentConfigRoute
  '/react19-demo': typeof React19DemoRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/chat/$agentId': typeof ChatAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-config'
    | '/react19-demo'
    | '/agent/$agentId'
    | '/chat/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-config'
    | '/react19-demo'
    | '/agent/$agentId'
    | '/chat/$agentId'
  id:
    | '__root__'
    | '/'
    | '/agent-config'
    | '/react19-demo'
    | '/agent/$agentId'
    | '/chat/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentConfigRoute: typeof AgentConfigRoute
  React19DemoRoute: typeof React19DemoRoute
  AgentAgentIdRoute: typeof AgentAgentIdRoute
  ChatAgentIdRoute: typeof ChatAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-config': {
      id: '/agent-config'
      path: '/agent-config'
      fullPath: '/agent-config'
      preLoaderRoute: typeof AgentConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react19-demo': {
      id: '/react19-demo'
      path: '/react19-demo'
      fullPath: '/react19-demo'
      preLoaderRoute: typeof React19DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$agentId': {
      id: '/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof AgentAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$agentId': {
      id: '/chat/$agentId'
      path: '/chat/$agentId'
      fullPath: '/chat/$agentId'
      preLoaderRoute: typeof ChatAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentConfigRoute: AgentConfigRoute,
  React19DemoRoute: React19DemoRoute,
  AgentAgentIdRoute: AgentAgentIdRoute,
  ChatAgentIdRoute: ChatAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
